// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="image_filter,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=13.500000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=12.771250,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=7,HLS_SYN_DSP=23,HLS_SYN_FF=1785,HLS_SYN_LUT=4974,HLS_VERSION=2018_3}" *)

module image_filter (
        input_V_data_V_dout,
        input_V_data_V_empty_n,
        input_V_data_V_read,
        input_V_keep_V_dout,
        input_V_keep_V_empty_n,
        input_V_keep_V_read,
        input_V_strb_V_dout,
        input_V_strb_V_empty_n,
        input_V_strb_V_read,
        input_V_user_V_dout,
        input_V_user_V_empty_n,
        input_V_user_V_read,
        input_V_last_V_dout,
        input_V_last_V_empty_n,
        input_V_last_V_read,
        input_V_id_V_dout,
        input_V_id_V_empty_n,
        input_V_id_V_read,
        input_V_dest_V_dout,
        input_V_dest_V_empty_n,
        input_V_dest_V_read,
        output_V_data_V_din,
        output_V_data_V_full_n,
        output_V_data_V_write,
        output_V_keep_V_din,
        output_V_keep_V_full_n,
        output_V_keep_V_write,
        output_V_strb_V_din,
        output_V_strb_V_full_n,
        output_V_strb_V_write,
        output_V_user_V_din,
        output_V_user_V_full_n,
        output_V_user_V_write,
        output_V_last_V_din,
        output_V_last_V_full_n,
        output_V_last_V_write,
        output_V_id_V_din,
        output_V_id_V_full_n,
        output_V_id_V_write,
        output_V_dest_V_din,
        output_V_dest_V_full_n,
        output_V_dest_V_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle
);


input  [7:0] input_V_data_V_dout;
input   input_V_data_V_empty_n;
output   input_V_data_V_read;
input  [0:0] input_V_keep_V_dout;
input   input_V_keep_V_empty_n;
output   input_V_keep_V_read;
input  [0:0] input_V_strb_V_dout;
input   input_V_strb_V_empty_n;
output   input_V_strb_V_read;
input  [0:0] input_V_user_V_dout;
input   input_V_user_V_empty_n;
output   input_V_user_V_read;
input  [0:0] input_V_last_V_dout;
input   input_V_last_V_empty_n;
output   input_V_last_V_read;
input  [0:0] input_V_id_V_dout;
input   input_V_id_V_empty_n;
output   input_V_id_V_read;
input  [0:0] input_V_dest_V_dout;
input   input_V_dest_V_empty_n;
output   input_V_dest_V_read;
output  [7:0] output_V_data_V_din;
input   output_V_data_V_full_n;
output   output_V_data_V_write;
output  [0:0] output_V_keep_V_din;
input   output_V_keep_V_full_n;
output   output_V_keep_V_write;
output  [0:0] output_V_strb_V_din;
input   output_V_strb_V_full_n;
output   output_V_strb_V_write;
output  [0:0] output_V_user_V_din;
input   output_V_user_V_full_n;
output   output_V_user_V_write;
output  [0:0] output_V_last_V_din;
input   output_V_last_V_full_n;
output   output_V_last_V_write;
output  [0:0] output_V_id_V_din;
input   output_V_id_V_full_n;
output   output_V_id_V_write;
output  [0:0] output_V_dest_V_din;
input   output_V_dest_V_full_n;
output   output_V_dest_V_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;

wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire   [10:0] Block_proc_U0_img_input_rows_V_out_din;
wire    Block_proc_U0_img_input_rows_V_out_write;
wire   [10:0] Block_proc_U0_img_input_cols_V_out_din;
wire    Block_proc_U0_img_input_cols_V_out_write;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_start_out;
wire    AXIvideo2Mat_U0_start_write;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read;
wire    AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read;
wire    AXIvideo2Mat_U0_img_rows_V_read;
wire    AXIvideo2Mat_U0_img_cols_V_read;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_V_write;
wire   [10:0] AXIvideo2Mat_U0_img_rows_V_out_din;
wire    AXIvideo2Mat_U0_img_rows_V_out_write;
wire   [10:0] AXIvideo2Mat_U0_img_cols_V_out_din;
wire    AXIvideo2Mat_U0_img_cols_V_out_write;
wire    GaussianBlur_U0_ap_start;
wire    GaussianBlur_U0_ap_done;
wire    GaussianBlur_U0_ap_continue;
wire    GaussianBlur_U0_ap_idle;
wire    GaussianBlur_U0_ap_ready;
wire    GaussianBlur_U0_start_out;
wire    GaussianBlur_U0_start_write;
wire    GaussianBlur_U0_p_src_rows_V_read;
wire    GaussianBlur_U0_p_src_cols_V_read;
wire    GaussianBlur_U0_p_src_data_stream_V_read;
wire   [7:0] GaussianBlur_U0_p_dst_data_stream_V_din;
wire    GaussianBlur_U0_p_dst_data_stream_V_write;
wire    Mat2AXIvideo_U0_ap_start;
wire    Mat2AXIvideo_U0_ap_done;
wire    Mat2AXIvideo_U0_ap_continue;
wire    Mat2AXIvideo_U0_ap_idle;
wire    Mat2AXIvideo_U0_ap_ready;
wire    Mat2AXIvideo_U0_img_data_stream_V_read;
wire   [7:0] Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write;
wire   [0:0] Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write;
wire   [0:0] Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write;
wire   [0:0] Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write;
wire   [0:0] Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write;
wire   [0:0] Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write;
wire   [0:0] Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din;
wire    Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write;
wire    ap_sync_continue;
wire    img_input_rows_V_c_full_n;
wire   [10:0] img_input_rows_V_c_dout;
wire    img_input_rows_V_c_empty_n;
wire    img_input_cols_V_c_full_n;
wire   [10:0] img_input_cols_V_c_dout;
wire    img_input_cols_V_c_empty_n;
wire    img_input_data_strea_full_n;
wire   [7:0] img_input_data_strea_dout;
wire    img_input_data_strea_empty_n;
wire    img_input_rows_V_c6_full_n;
wire   [10:0] img_input_rows_V_c6_dout;
wire    img_input_rows_V_c6_empty_n;
wire    img_input_cols_V_c7_full_n;
wire   [10:0] img_input_cols_V_c7_dout;
wire    img_input_cols_V_c7_empty_n;
wire    filtered_data_stream_full_n;
wire   [7:0] filtered_data_stream_dout;
wire    filtered_data_stream_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_proc_U0_ap_ready;
wire    ap_sync_Block_proc_U0_ap_ready;
reg   [1:0] Block_proc_U0_ap_ready_count;
reg    ap_sync_reg_AXIvideo2Mat_U0_ap_ready;
wire    ap_sync_AXIvideo2Mat_U0_ap_ready;
reg   [1:0] AXIvideo2Mat_U0_ap_ready_count;
wire    Block_proc_U0_start_full_n;
wire    Block_proc_U0_start_write;
wire   [0:0] start_for_GaussianBlur_U0_din;
wire    start_for_GaussianBlur_U0_full_n;
wire   [0:0] start_for_GaussianBlur_U0_dout;
wire    start_for_GaussianBlur_U0_empty_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_din;
wire    start_for_Mat2AXIvideo_U0_full_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_dout;
wire    start_for_Mat2AXIvideo_U0_empty_n;
wire    Mat2AXIvideo_U0_start_full_n;
wire    Mat2AXIvideo_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_Block_proc_U0_ap_ready = 1'b0;
#0 Block_proc_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_AXIvideo2Mat_U0_ap_ready = 1'b0;
#0 AXIvideo2Mat_U0_ap_ready_count = 2'd0;
end

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Block_proc_U0_ap_start),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .img_input_rows_V_out_din(Block_proc_U0_img_input_rows_V_out_din),
    .img_input_rows_V_out_full_n(img_input_rows_V_c_full_n),
    .img_input_rows_V_out_write(Block_proc_U0_img_input_rows_V_out_write),
    .img_input_cols_V_out_din(Block_proc_U0_img_input_cols_V_out_din),
    .img_input_cols_V_out_full_n(img_input_cols_V_c_full_n),
    .img_input_cols_V_out_write(Block_proc_U0_img_input_cols_V_out_write)
);

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .start_full_n(start_for_GaussianBlur_U0_full_n),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .start_out(AXIvideo2Mat_U0_start_out),
    .start_write(AXIvideo2Mat_U0_start_write),
    .AXI_video_strm_V_data_V_dout(input_V_data_V_dout),
    .AXI_video_strm_V_data_V_empty_n(input_V_data_V_empty_n),
    .AXI_video_strm_V_data_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read),
    .AXI_video_strm_V_keep_V_dout(input_V_keep_V_dout),
    .AXI_video_strm_V_keep_V_empty_n(input_V_keep_V_empty_n),
    .AXI_video_strm_V_keep_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read),
    .AXI_video_strm_V_strb_V_dout(input_V_strb_V_dout),
    .AXI_video_strm_V_strb_V_empty_n(input_V_strb_V_empty_n),
    .AXI_video_strm_V_strb_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read),
    .AXI_video_strm_V_user_V_dout(input_V_user_V_dout),
    .AXI_video_strm_V_user_V_empty_n(input_V_user_V_empty_n),
    .AXI_video_strm_V_user_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read),
    .AXI_video_strm_V_last_V_dout(input_V_last_V_dout),
    .AXI_video_strm_V_last_V_empty_n(input_V_last_V_empty_n),
    .AXI_video_strm_V_last_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read),
    .AXI_video_strm_V_id_V_dout(input_V_id_V_dout),
    .AXI_video_strm_V_id_V_empty_n(input_V_id_V_empty_n),
    .AXI_video_strm_V_id_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read),
    .AXI_video_strm_V_dest_V_dout(input_V_dest_V_dout),
    .AXI_video_strm_V_dest_V_empty_n(input_V_dest_V_empty_n),
    .AXI_video_strm_V_dest_V_read(AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read),
    .img_rows_V_dout(img_input_rows_V_c_dout),
    .img_rows_V_empty_n(img_input_rows_V_c_empty_n),
    .img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read),
    .img_cols_V_dout(img_input_cols_V_c_dout),
    .img_cols_V_empty_n(img_input_cols_V_c_empty_n),
    .img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read),
    .img_data_stream_V_din(AXIvideo2Mat_U0_img_data_stream_V_din),
    .img_data_stream_V_full_n(img_input_data_strea_full_n),
    .img_data_stream_V_write(AXIvideo2Mat_U0_img_data_stream_V_write),
    .img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .img_rows_V_out_full_n(img_input_rows_V_c6_full_n),
    .img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .img_cols_V_out_full_n(img_input_cols_V_c7_full_n),
    .img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write)
);

GaussianBlur GaussianBlur_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(GaussianBlur_U0_ap_start),
    .start_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .ap_done(GaussianBlur_U0_ap_done),
    .ap_continue(GaussianBlur_U0_ap_continue),
    .ap_idle(GaussianBlur_U0_ap_idle),
    .ap_ready(GaussianBlur_U0_ap_ready),
    .start_out(GaussianBlur_U0_start_out),
    .start_write(GaussianBlur_U0_start_write),
    .p_src_rows_V_dout(img_input_rows_V_c6_dout),
    .p_src_rows_V_empty_n(img_input_rows_V_c6_empty_n),
    .p_src_rows_V_read(GaussianBlur_U0_p_src_rows_V_read),
    .p_src_cols_V_dout(img_input_cols_V_c7_dout),
    .p_src_cols_V_empty_n(img_input_cols_V_c7_empty_n),
    .p_src_cols_V_read(GaussianBlur_U0_p_src_cols_V_read),
    .p_src_data_stream_V_dout(img_input_data_strea_dout),
    .p_src_data_stream_V_empty_n(img_input_data_strea_empty_n),
    .p_src_data_stream_V_read(GaussianBlur_U0_p_src_data_stream_V_read),
    .p_dst_data_stream_V_din(GaussianBlur_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(filtered_data_stream_full_n),
    .p_dst_data_stream_V_write(GaussianBlur_U0_p_dst_data_stream_V_write)
);

Mat2AXIvideo Mat2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(Mat2AXIvideo_U0_ap_start),
    .ap_done(Mat2AXIvideo_U0_ap_done),
    .ap_continue(Mat2AXIvideo_U0_ap_continue),
    .ap_idle(Mat2AXIvideo_U0_ap_idle),
    .ap_ready(Mat2AXIvideo_U0_ap_ready),
    .img_data_stream_V_dout(filtered_data_stream_dout),
    .img_data_stream_V_empty_n(filtered_data_stream_empty_n),
    .img_data_stream_V_read(Mat2AXIvideo_U0_img_data_stream_V_read),
    .AXI_video_strm_V_data_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din),
    .AXI_video_strm_V_data_V_full_n(output_V_data_V_full_n),
    .AXI_video_strm_V_data_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write),
    .AXI_video_strm_V_keep_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din),
    .AXI_video_strm_V_keep_V_full_n(output_V_keep_V_full_n),
    .AXI_video_strm_V_keep_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write),
    .AXI_video_strm_V_strb_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din),
    .AXI_video_strm_V_strb_V_full_n(output_V_strb_V_full_n),
    .AXI_video_strm_V_strb_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write),
    .AXI_video_strm_V_user_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din),
    .AXI_video_strm_V_user_V_full_n(output_V_user_V_full_n),
    .AXI_video_strm_V_user_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write),
    .AXI_video_strm_V_last_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din),
    .AXI_video_strm_V_last_V_full_n(output_V_last_V_full_n),
    .AXI_video_strm_V_last_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write),
    .AXI_video_strm_V_id_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din),
    .AXI_video_strm_V_id_V_full_n(output_V_id_V_full_n),
    .AXI_video_strm_V_id_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write),
    .AXI_video_strm_V_dest_V_din(Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din),
    .AXI_video_strm_V_dest_V_full_n(output_V_dest_V_full_n),
    .AXI_video_strm_V_dest_V_write(Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write)
);

fifo_w11_d2_A img_input_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_img_input_rows_V_out_din),
    .if_full_n(img_input_rows_V_c_full_n),
    .if_write(Block_proc_U0_img_input_rows_V_out_write),
    .if_dout(img_input_rows_V_c_dout),
    .if_empty_n(img_input_rows_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_rows_V_read)
);

fifo_w11_d2_A img_input_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_img_input_cols_V_out_din),
    .if_full_n(img_input_cols_V_c_full_n),
    .if_write(Block_proc_U0_img_input_cols_V_out_write),
    .if_dout(img_input_cols_V_c_dout),
    .if_empty_n(img_input_cols_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_cols_V_read)
);

fifo_w8_d2_A img_input_data_strea_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_V_din),
    .if_full_n(img_input_data_strea_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_V_write),
    .if_dout(img_input_data_strea_dout),
    .if_empty_n(img_input_data_strea_empty_n),
    .if_read(GaussianBlur_U0_p_src_data_stream_V_read)
);

fifo_w11_d2_A img_input_rows_V_c6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .if_full_n(img_input_rows_V_c6_full_n),
    .if_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .if_dout(img_input_rows_V_c6_dout),
    .if_empty_n(img_input_rows_V_c6_empty_n),
    .if_read(GaussianBlur_U0_p_src_rows_V_read)
);

fifo_w11_d2_A img_input_cols_V_c7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .if_full_n(img_input_cols_V_c7_full_n),
    .if_write(AXIvideo2Mat_U0_img_cols_V_out_write),
    .if_dout(img_input_cols_V_c7_dout),
    .if_empty_n(img_input_cols_V_c7_empty_n),
    .if_read(GaussianBlur_U0_p_src_cols_V_read)
);

fifo_w8_d2_A filtered_data_stream_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(GaussianBlur_U0_p_dst_data_stream_V_din),
    .if_full_n(filtered_data_stream_full_n),
    .if_write(GaussianBlur_U0_p_dst_data_stream_V_write),
    .if_dout(filtered_data_stream_dout),
    .if_empty_n(filtered_data_stream_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_V_read)
);

start_for_Gaussiazec start_for_Gaussiazec_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_GaussianBlur_U0_din),
    .if_full_n(start_for_GaussianBlur_U0_full_n),
    .if_write(AXIvideo2Mat_U0_start_write),
    .if_dout(start_for_GaussianBlur_U0_dout),
    .if_empty_n(start_for_GaussianBlur_U0_empty_n),
    .if_read(GaussianBlur_U0_ap_ready)
);

start_for_Mat2AXIAem start_for_Mat2AXIAem_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Mat2AXIvideo_U0_din),
    .if_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .if_write(GaussianBlur_U0_start_write),
    .if_dout(start_for_Mat2AXIvideo_U0_dout),
    .if_empty_n(start_for_Mat2AXIvideo_U0_empty_n),
    .if_read(Mat2AXIvideo_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_AXIvideo2Mat_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready <= ap_sync_AXIvideo2Mat_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_Block_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_proc_U0_ap_ready <= ap_sync_Block_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (1'b0 == AXIvideo2Mat_U0_ap_ready))) begin
        AXIvideo2Mat_U0_ap_ready_count <= (AXIvideo2Mat_U0_ap_ready_count - 2'd1);
    end else if (((1'b1 == AXIvideo2Mat_U0_ap_ready) & (ap_sync_ready == 1'b0))) begin
        AXIvideo2Mat_U0_ap_ready_count <= (AXIvideo2Mat_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (1'b0 == Block_proc_U0_ap_ready))) begin
        Block_proc_U0_ap_ready_count <= (Block_proc_U0_ap_ready_count - 2'd1);
    end else if (((1'b1 == Block_proc_U0_ap_ready) & (ap_sync_ready == 1'b0))) begin
        Block_proc_U0_ap_ready_count <= (Block_proc_U0_ap_ready_count + 2'd1);
    end
end

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = ((ap_sync_reg_AXIvideo2Mat_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_proc_U0_ap_continue = 1'b1;

assign Block_proc_U0_ap_start = ((ap_sync_reg_Block_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_proc_U0_start_full_n = 1'b1;

assign Block_proc_U0_start_write = 1'b0;

assign GaussianBlur_U0_ap_continue = 1'b1;

assign GaussianBlur_U0_ap_start = start_for_GaussianBlur_U0_empty_n;

assign Mat2AXIvideo_U0_ap_continue = 1'b1;

assign Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n;

assign Mat2AXIvideo_U0_start_full_n = 1'b1;

assign Mat2AXIvideo_U0_start_write = 1'b0;

assign ap_done = Mat2AXIvideo_U0_ap_done;

assign ap_idle = (Mat2AXIvideo_U0_ap_idle & GaussianBlur_U0_ap_idle & Block_proc_U0_ap_idle & AXIvideo2Mat_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_AXIvideo2Mat_U0_ap_ready = (ap_sync_reg_AXIvideo2Mat_U0_ap_ready | AXIvideo2Mat_U0_ap_ready);

assign ap_sync_Block_proc_U0_ap_ready = (ap_sync_reg_Block_proc_U0_ap_ready | Block_proc_U0_ap_ready);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Mat2AXIvideo_U0_ap_done;

assign ap_sync_ready = (ap_sync_Block_proc_U0_ap_ready & ap_sync_AXIvideo2Mat_U0_ap_ready);

assign input_V_data_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_data_V_read;

assign input_V_dest_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_dest_V_read;

assign input_V_id_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_id_V_read;

assign input_V_keep_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_keep_V_read;

assign input_V_last_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_last_V_read;

assign input_V_strb_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_strb_V_read;

assign input_V_user_V_read = AXIvideo2Mat_U0_AXI_video_strm_V_user_V_read;

assign output_V_data_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_data_V_din;

assign output_V_data_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_data_V_write;

assign output_V_dest_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_din;

assign output_V_dest_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_dest_V_write;

assign output_V_id_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_id_V_din;

assign output_V_id_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_id_V_write;

assign output_V_keep_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_din;

assign output_V_keep_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_keep_V_write;

assign output_V_last_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_last_V_din;

assign output_V_last_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_last_V_write;

assign output_V_strb_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_din;

assign output_V_strb_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_strb_V_write;

assign output_V_user_V_din = Mat2AXIvideo_U0_AXI_video_strm_V_user_V_din;

assign output_V_user_V_write = Mat2AXIvideo_U0_AXI_video_strm_V_user_V_write;

assign start_for_GaussianBlur_U0_din = 1'b1;

assign start_for_Mat2AXIvideo_U0_din = 1'b1;

endmodule //image_filter
